# Generated by Django 5.1.15 on 2026-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_true_false',
            field=models.BooleanField(default=False, verbose_name='แบบถูก/ผิด'),
        ),
    ]
