# Generated by Django 5.1.15 on 2026-08-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_is_true_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='source_file',
            field=models.FileField(blank=True, help_text='ไฟล์ต้นฉบับของแบบทดสอบนี้ (ถ้ามี) เช่นไฟล์ Word ที่ใช้สร้างคำถาม', null=True, upload_to='quiz_sources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
    ]
