# Generated by Django 5.1.15 on 2026-08-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_quiz_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='kind',
            field=models.CharField(choices=[('pretest', 'แบบทดสอบก่อนเรียน'), ('posttest', 'แบบทดสอบหลังเรียน'), ('invideo', 'คำถามระหว่างวิดีโอ'), ('retest', 'แบบทดสอบหลังเรียน (ชุดเดียวกับก่อนเรียน)')], max_length=10),
        ),
    ]
