# Generated by Django 5.1.15 on 2026-08-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_quiz_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='kind',
            field=models.CharField(choices=[('pretest', 'แบบทดสอบก่อนเรียน'), ('posttest', 'แบบทดสอบหลังเรียน'), ('invideo', 'คำถามระหว่างวิดีโอ'), ('retest', 'แบบทดสอบหลังเรียน')], max_length=10),
        ),
    ]
