# Generated by Django 5.1.15 on 2026-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_notes',
            field=models.TextField(blank=True, help_text='เนื้อหา/สรุปบทเรียนแบบละเอียด ใช้เป็นข้อมูลอ้างอิงให้ AI ผู้ช่วยตอบคำถามนักเรียนเฉพาะเรื่องนี้เท่านั้น'),
        ),
    ]
