# Generated by Django 5.1.15 on 2026-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_content_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='อัปโหลดรูปปกจากเครื่อง (ไม่บังคับ)', null=True, upload_to='course_covers/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, help_text='หรือใส่ลิงก์รูปปกจากอินเทอร์เน็ต (ไม่บังคับ)'),
        ),
    ]
