# Generated by Django 5.1.15 on 2026-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_cover_image_alter_course_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='หรืออัปโหลดไฟล์วิดีโอโดยตรงจากเครื่อง (MP4 แนะนำ)', null=True, upload_to='lesson_videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='ลิงก์วิดีโอ YouTube ของบทเรียนนี้'),
        ),
    ]
