# Generated by Django 5.1.15 on 2026-08-23 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_video_file_alter_lesson_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slide_file',
            field=models.FileField(blank=True, help_text='ไฟล์เอกสารประกอบการเรียน (PDF หรือ PowerPoint)', null=True, upload_to='lesson_slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])]),
        ),
    ]
