# Generated by Django 5.1.15 on 2026-08-23 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_slide_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='extra_file',
            field=models.FileField(blank=True, help_text='เอกสารเสริมเพิ่มเติม (ถ้ามี)', null=True, upload_to='lesson_extras/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])]),
        ),
    ]
